### ISSUE TITLE
prepend of www in URL seems to break auth

### ISSUE THREAD

**Issue by anthonyrowe** [arenaxr/arena-account#81]
Load a full URL like: http://www.arenaxr.org including the www. and then if you go to login or directly to a page it internally has a 400 error.  It seems like without the www the same flows / pages are ok.

**Comment by mwfarb** [comment]
Hm, I have questions. I'll check in the morning.

**Comment by mwfarb** [comment]
For now, we've added redirection from www.arenaxr.org to arenaxr.org in nginx.
