### ISSUE TITLE
File Store Page Fails New Users

### ISSUE THREAD

**Issue by mwfarb** [arenaxr/arena-account#96]
The filestore page seems to work for admin account but no others on firefox on arenaxr.org.

Console:
```
Cookie “auth” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by nampereira** [comment]
Filestore has this setting
![image](https://github.com/arenaxr/arena-account/assets/3504501/4418c61a-d268-4f71-8182-1e9ad94cce1f)

So, it should create, I think.

**Comment by nampereira** [comment]
I see @mwfarb, you think the fs endpoint to create a new user does not implement the home dir creation. But didn't this work before ?

**Comment by mwfarb** [comment]
Good point, but I'm not sure. I'll have to simulate when I get a chance.

**Comment by mwfarb** [comment]
Tried local dev and it has the same behavior, new user inserted, no user dir.

Think I fixed it. The POST users handler creates the dir only when "scope" is set: https://github.com/arenaxr/arena-account/commit/577b8e111114ff210dbd5a43a197ead5c55cfece

**Comment by mwfarb** [comment]
Might need to also run two requests for staff, POST for new user, with user scope to create user dir, and also a follow up PUT to update user scope to root.
